"""empty message

Revision ID: 08228b4785c6
Revises: 
Create Date: 2022-06-03 08:11:47.719405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08228b4785c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
