name: Test JMeter Action

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Load Testing
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: warehouse-test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"